fix PolymorphicJsonAdapterFactory with FallbackJsonAdapter deserialize empty object error.
square/moshi pull request #1623
Opened 2023-01-31 12:20 UTC by coofee

2023-01-31 14:46 UTC, ZacSweers commented
Can you please write a description explaining the PR changes?

2023-02-01 02:44 UTC, coofee commented
> its my fault，already update now，please review again。

2023-02-25 17:56 UTC, ZacSweers requested changes

2023-02-25 17:56 UTC, ZacSweers commented on moshi-adapters/src/test/java/com/squareup/moshi/adapters/PolymorphicJsonAdapterFactoryTest.java
> +import static org.junit.Assert.assertNotNull;
Please use Truth assertions

2023-04-23 01:54 UTC, closed without merging